#ifndef _DEF_MENU_H
#define _DEF_MENU_H

/*

0: Home
1: Main Menu
   2: PID Menu
      > P
      > I
      > D
   3: Favs Menu
      12: F1
      >   F1-Name
      >   F1-Temp
      13: F2
      >   F2-Name
      >   F2-Temp
      14: F3
      >   F3-Name
      >   F3-Temp
      15: F4
      >   F4-Name
      >   F4-Temp
   4: Bump Menu
      > Bump Amount
      > Bump Time
   5: System Menu
      > Knob Adjustment Amount
      > Turn off when Idle
      > Idle shutoff length
      > Factory Reset
      > Check for Update
      11: Display Settings
          > Backlight Brightness
          > Auto Dim
          > Auto Dim Timeout
      > Knob diagram on/off
      > Theme Selection?
   6: LED Menu
   7: WiFi Menu
      >   Scan Networks
      16: Nearby Networks
      17: Password
      >   Show Password
      >   Join Network
      >   Delete stored network
      18: Hostname
   8: BLE Settings
      > Enable
      > Monitor
   9: USB Settings
      > Enable
      > Monitor
      > Discover
  10: Power Settings
      > Reset
      > Power Off
  11: Clock Setup
      > Date Set
      > Time Set
      > Alarm Setup
      > Timer Setup
*/

enum MENU_ROOT
{
    MENU_ROOT = 0,
    MENU_ROOT_HOME = 1, // Home screen
    MENU_ROOT_MAIN = 2, // Main menu
};

enum MENU_MAIN
{
    MENU_MAIN_PID = 3,       // 130
    MENU_MAIN_FAVS = 4,      // 140
    MENU_MAIN_BUMP = 5,      // 150
    MENU_MAIN_DISPLAY = 166, // 30
    MENU_MAIN_SYSTEM = 6,    // 160
    MENU_MAIN_LED = 7,       // 170
    MENU_MAIN_WIFI = 8,      // 180
    MENU_MAIN_BLE = 9,       // 190
    MENU_MAIN_USB = 10,      // 200
    MENU_MAIN_POWER = 11,    // 210
    MENU_MAIN_CLOCK = 12,    // 220
    MENU_MAIN_GRAPH = 13,    // 330
    MENU_MAIN_VERSION = 14
};

enum MENU_PID
{
    MENU_PID_P = 132,
    MENU_PID_I = 133,
    MENU_PID_D = 134,
    MENU_PID_TUNING = 139,
    MENU_PID_AUTO = 131,
    MENU_PID_PWM_BIAS = 1340,
    MENU_PID_WINDUP_LIMIT = 1341,
    MENU_PID_PWM_FACTOR = 135,
    MENU_PID_PWM_CYCLE = 136,
    MENU_PID_PWM_FREQ = 137,
    MENU_PID_PWM_BITS = 138,
    MENU_PID_MEASURE_MODE = 129,
};

enum MENU_PID_FUNC
{
    MENU_PID_AUTO_TOGGLE = 1131,
    MENU_PID_PWM_BIAS_VAR = 1134,
    MENU_PID_PWM_FACTOR_VAR = 1135,
    MENU_PID_WINDUP_LIMIT_VAR = 1133,
    MENU_PID_PWM_CYCLE_VAR = 1136,
    MENU_PID_PWM_FREQ_VAR = 1137,
    MENU_PID_PWM_BITS_VAR = 1138,
    MENU_PID_MEASURE_MODE_VAR = 1129,
};

enum MENU_FAVS
{
    MENU_FAV_1 = 141,
    MENU_FAV_2 = 142,
    MENU_FAV_3 = 143,
    MENU_FAV_4 = 144,
};

enum MENU_FAV_1E // 230
{
    MENU_FAV_1N = 231,
    MENU_FAV_1T = 232,
};

enum MENU_FAV_2E
{
    MENU_FAV_2N = 233,
    MENU_FAV_2T = 234,
};

enum MENU_FAV_3E
{
    MENU_FAV_3N = 235,
    MENU_FAV_3T = 236,
};

enum MENU_FAV_4E
{
    MENU_FAV_4N = 237,
    MENU_FAV_4T = 238,
};

enum MENU_FAV_NAMEDEF
{
    MENU_FAV_NAME_FAVORITE1 = 240,
    MENU_FAV_NAME_FAVORITE2 = 241,
    MENU_FAV_NAME_FAVORITE3 = 242,
    MENU_FAV_NAME_FAVORITE4 = 243,
    MENU_FAV_NAME_HIGH = 244,
    MENU_FAV_NAME_MEDIUM = 245,
    MENU_FAV_NAME_LOW = 246,
    MENU_FAV_NAME_STAYWARM = 247,
    MENU_FAV_NAME_MAIN = 248,
    MENU_FAV_NAME_HOME = 249,
    MENU_FAV_NAME_CLEAN = 250,
    MENU_FAV_NAME_PREHEAT = 251,
    MENU_FAV_NAME_STAGE1 = 252,
    MENU_FAV_NAME_STAGE2 = 253,
    MENU_FAV_NAME_STAGE3 = 254,
    MENU_FAV_NAME_STAGE4 = 255,
    MENU_FAV_NAME_ONE = 256,
    MENU_FAV_NAME_TWO = 257,
    MENU_FAV_NAME_THREE = 258,
    MENU_FAV_NAME_FOUR = 259,
    MENU_FAV_NAME_COOLDOWN = 260,
    MENU_FAV_NAME_PURGE = 261,
    MENU_FAV_NAME_PRESS = 262,
    MENU_FAV_NAME_SOUSVIDE = 263,
    MENU_FAV_NAME_SMOKE = 264,
    MENU_FAV_NAME_TOAST = 265,
    MENU_FAV_NAME_DRY = 266,
    MENU_FAV_NAME_DEHUMIDIFY = 267,
    MENU_FAV_NAME_TEMPER = 268,
    MENU_FAV_NAME_BAKE = 269,
    MENU_FAV_NAME_SOAK = 270,
    MENU_FAV_NAME_REFLOW = 271,
    MENU_FAV_NAME_RED = 273,
    MENU_FAV_NAME_GREEN = 274,
    MENU_FAV_NAME_BLUE = 275,
};

enum MENU_BUMP
{
    MENU_BUMP_AMOUNT = 150, // Bump Amount
    MENU_BUMP_TIME = 151,   // Bump Time
};

enum MENU_GRAPH
{
    MENU_GRAPH_TEMPERATURE = 370,
    MENU_GRAPH_TEMPERATURE_ZOOM = 371,
    MENU_GRAPH_TEMPERATURE_LONG = 372,
    MENU_GRAPH_TEMPERATURE_0 = 373,
    MENU_GRAPH_TEMPERATURE_ZOOM_0 = 374,
    MENU_GRAPH_TEMPERATURE_LONG_0 = 375,
    MENU_GRAPH_TEMPERATURE_1 = 376,
    MENU_GRAPH_TEMPERATURE_ZOOM_1 = 377,
    MENU_GRAPH_TEMPERATURE_LONG_1 = 378,
};

enum MENU_SYSTEM
{
    MENU_SYSTEM_LOCAL_TEMPERATURE = 160, // Onboard Temperatures
    MENU_SYSTEM_KNOB_ADJUST = 161,       // Knob Adjustments
    MENU_SYSTEM_TOGGLE_IDLE = 162,       // Turn off when Idle
    MENU_SYSTEM_LENGTH_IDLE = 163,       // Idle shutoff length
    MENU_SYSTEM_FACTORY_RESET = 164,     // Factory Reset
    MENU_SYSTEM_UPDATE_CHECK = 165,      // Check for Update
    MENU_SYSTEM_DISPLAY_SETTINGS = 166,  // Display Settings (30)
    MENU_SYSTEM_THEME = 168,             // Theme Selection?
    MENU_SYSTEM_TOGGLE_IDLE_VAR = 1162,
    MENU_SYSTEM_LENGTH_IDLE_VAR = 1163,
    MENU_SYSTEM_FACTORY_RESET_CONFIRM = 1164,

};
enum MENU_KNOB_ADJUST
{
    MENU_KNOB_ADJUST_AMOUNT = 25,  // Knob Adjustment Amount
    MENU_KNOB_ADJUST_INVERT = 26,  // Knob Inversion Toggle
    MENU_KNOB_DIAGRAM_SHOWN = 167, // Knob diagram on/off
};

enum MENU_LOCAL_TEMPERATURE
{
    MENU_LOCAL_CELSIUS_TOGGLE = 20,
    MENU_LOCAL_TEMPERATURE_1 = 21,
    MENU_LOCAL_TEMPERATURE_2 = 22,
    MENU_LOCAL_TEMPERATURE_3 = 23,
    MENU_LOCAL_FAN_CONTROL = 29,
};

enum MENU_FAN_CONTROL
{
    MENU_FAN_CONTROL_ENABLED = 90,
    MENU_FAN_CONTROL_MODE = 91,
    MENU_FAN_CONTROL_SPEED = 92,
};

enum MENU_DISPLAY
{
    MENU_DISPLAY_BACKLIGHT = 30,   // Backlight Brightness
    MENU_DISPLAY_AUTO_DIM = 31,    // Auto Dim
    MENU_DISPLAY_TIMEOUT_DIM = 32, // Auto Dim Timeout
    MENU_DISPLAY_SCREENSAVER = 33, // Screensaver Toggle
    MENU_DISPLAY_SCREENTIME = 33,  // Screensaver Timeout (deprecated)
    MENU_DISPLAY_SYS_TRAY = 34,
    MENU_DISPLAY_BACKLIGHT_VAR = 3030,
    MENU_DISPLAY_BACKLIGHT_MIN_VAR = 3035,
    MENU_DISPLAY_AUTO_DIM_VAR = 3031,
    MENU_DISPLAY_TIMEOUT_DIM_VAR = 3032,

};

enum MENU_SCREENSAVER
{
    MENU_SCREENSAVER_TIME = 45,
    MENU_SCREENSAVER_ENABLED = 46,
    MENU_SCREENSAVER_TOGGLE = 47,
    MENU_SCREENSAVER_STARS = 48,
};

enum MENU_LED
{
    MENU_LED_MAIN_TOGGLE = 170,
    MENU_LED_SETUP = 171,
    MENU_LED_STATUS = 172,
    /*MENU_LED_AMBIENT = 173,*/
    MENU_LED_PRESET = 174,
};

enum MENU_LED_PRESETS
{
    // MENU_LED_PRESET_TOGGLE = 280,
    MENU_LED_RWAVE = 281,
    MENU_LED_RAINBOW = 282,
    MENU_LED_RPULSE = 283,
    MENU_LED_CSHIFT = 284,
    MENU_LED_CPULSE = 285,
    MENU_LED_ASTATIC = 286,
    MENU_LED_ABLINK = 287,
    MENU_LED_APULSE = 288,
};

enum MENU_LED_AMBIENTS
{
    MENU_LED_AMBIENT_TOGGLE = 290,
    MENU_LED_ABLINK_OLD = 291,
    MENU_LED_APULSE_OLD = 292,
};

enum MENU_LED_STAT
{
    MENU_LED_STATUS_TOGGLE = 297,
};

enum MENU_LED_COLOR
{
    MENU_LED_BRIGHTNESS = 298,
    MENU_LED_COLOR = 299,
};

enum MENU_LED_COLORLIST
{
    MENU_COLOR_MAROON = 4001,
    MENU_COLOR_DARK_RED,
    MENU_COLOR_BROWN,
    MENU_COLOR_FIREBRICK,
    MENU_COLOR_CRIMSON,
    MENU_COLOR_RED,
    MENU_COLOR_TOMATO,
    MENU_COLOR_CORAL,
    MENU_COLOR_INDIAN_RED,
    MENU_COLOR_LIGHT_CORAL,
    MENU_COLOR_DARK_SALMON,
    MENU_COLOR_SALMON,
    MENU_COLOR_LIGHT_SALMON,
    MENU_COLOR_ORANGE_RED,
    MENU_COLOR_DARK_ORANGE,
    MENU_COLOR_ORANGE,
    MENU_COLOR_GOLD,
    MENU_COLOR_DARK_GOLDEN_ROD,
    MENU_COLOR_GOLDEN_ROD,
    MENU_COLOR_PALE_GOLDEN_ROD,
    MENU_COLOR_DARK_KHAKI,
    MENU_COLOR_KHAKI,
    MENU_COLOR_OLIVE,
    MENU_COLOR_YELLOW,
    MENU_COLOR_YELLOW_GREEN,
    MENU_COLOR_DARK_OLIVE_GREEN,
    MENU_COLOR_OLIVE_DRAB,
    MENU_COLOR_LAWN_GREEN,
    MENU_COLOR_CHARTREUSE,
    MENU_COLOR_GREEN_YELLOW,
    MENU_COLOR_DARK_GREEN,
    MENU_COLOR_GREEN,
    MENU_COLOR_FOREST_GREEN,
    MENU_COLOR_LIME,
    MENU_COLOR_LIME_GREEN,
    MENU_COLOR_LIGHT_GREEN,
    MENU_COLOR_PALE_GREEN,
    MENU_COLOR_DARK_SEA_GREEN,
    MENU_COLOR_MEDIUM_SPRING_GREEN,
    MENU_COLOR_SPRING_GREEN,
    MENU_COLOR_SEA_GREEN,
    MENU_COLOR_MEDIUM_AQUA_MARINE,
    MENU_COLOR_MEDIUM_SEA_GREEN,
    MENU_COLOR_LIGHT_SEA_GREEN,
    MENU_COLOR_DARK_SLATE_GRAY,
    MENU_COLOR_TEAL,
    MENU_COLOR_DARK_CYAN,
    MENU_COLOR_AQUA,
    MENU_COLOR_CYAN,
    MENU_COLOR_LIGHT_CYAN,
    MENU_COLOR_DARK_TURQUOISE,
    MENU_COLOR_TURQUOISE,
    MENU_COLOR_MEDIUM_TURQUOISE,
    MENU_COLOR_PALE_TURQUOISE,
    MENU_COLOR_AQUA_MARINE,
    MENU_COLOR_POWDER_BLUE,
    MENU_COLOR_CADET_BLUE,
    MENU_COLOR_STEEL_BLUE,
    MENU_COLOR_CORN_FLOWER_BLUE,
    MENU_COLOR_DEEP_SKY_BLUE,
    MENU_COLOR_DODGER_BLUE,
    MENU_COLOR_LIGHT_BLUE,
    MENU_COLOR_SKY_BLUE,
    MENU_COLOR_LIGHT_SKY_BLUE,
    MENU_COLOR_MIDNIGHT_BLUE,
    MENU_COLOR_NAVY,
    MENU_COLOR_DARK_BLUE,
    MENU_COLOR_MEDIUM_BLUE,
    MENU_COLOR_BLUE,
    MENU_COLOR_ROYAL_BLUE,
    MENU_COLOR_BLUE_VIOLET,
    MENU_COLOR_INDIGO,
    MENU_COLOR_DARK_SLATE_BLUE,
    MENU_COLOR_SLATE_BLUE,
    MENU_COLOR_MEDIUM_SLATE_BLUE,
    MENU_COLOR_MEDIUM_PURPLE,
    MENU_COLOR_DARK_MAGENTA,
    MENU_COLOR_DARK_VIOLET,
    MENU_COLOR_DARK_ORCHID,
    MENU_COLOR_MEDIUM_ORCHID,
    MENU_COLOR_PURPLE,
    MENU_COLOR_THISTLE,
    MENU_COLOR_PLUM,
    MENU_COLOR_VIOLET,
    MENU_COLOR_MAGENTA,
    MENU_COLOR_ORCHID,
    MENU_COLOR_MEDIUM_VIOLET_RED,
    MENU_COLOR_PALE_VIOLET_RED,
    MENU_COLOR_DEEP_PINK,
    MENU_COLOR_HOT_PINK,
    MENU_COLOR_LIGHT_PINK,
    MENU_COLOR_PINK,
    MENU_COLOR_ANTIQUE_WHITE,
    MENU_COLOR_BEIGE,
    MENU_COLOR_BISQUE,
    MENU_COLOR_BLANCHED_ALMOND,
    MENU_COLOR_WHEAT,
    MENU_COLOR_CORN_SILK,
    MENU_COLOR_LEMON_CHIFFON,
    MENU_COLOR_LIGHT_GOLDEN_ROD_YELLOW,
    MENU_COLOR_LIGHT_YELLOW,
    MENU_COLOR_SADDLE_BROWN,
    MENU_COLOR_SIENNA,
    MENU_COLOR_CHOCOLATE,
    MENU_COLOR_PERU,
    MENU_COLOR_SANDY_BROWN,
    MENU_COLOR_BURLY_WOOD,
    MENU_COLOR_TAN,
    MENU_COLOR_ROSY_BROWN,
    MENU_COLOR_MOCCASIN,
    MENU_COLOR_NAVAJO_WHITE,
    MENU_COLOR_PEACH_PUFF,
    MENU_COLOR_MISTY_ROSE,
    MENU_COLOR_LAVENDER_BLUSH,
    MENU_COLOR_LINEN,
    MENU_COLOR_OLD_LACE,
    MENU_COLOR_PAPAYA_WHIP,
    MENU_COLOR_SEA_SHELL,
    MENU_COLOR_MINT_CREAM,
    MENU_COLOR_SLATE_GRAY,
    MENU_COLOR_LIGHT_SLATE_GRAY,
    MENU_COLOR_LIGHT_STEEL_BLUE,
    MENU_COLOR_LAVENDER,
    MENU_COLOR_FLORAL_WHITE,
    MENU_COLOR_ALICE_BLUE,
    MENU_COLOR_GHOST_WHITE,
    MENU_COLOR_HONEY_DEW,
    MENU_COLOR_IVORY,
    MENU_COLOR_AZURE,
    MENU_COLOR_SNOW,
    MENU_COLOR_BLACK,
    MENU_COLOR_DIM_GRAY,
    MENU_COLOR_GRAY,
    MENU_COLOR_DARK_GRAY,
    MENU_COLOR_SILVER,
    MENU_COLOR_LIGHT_GRAY,
    MENU_COLOR_GAINSBORO,
    MENU_COLOR_WHITE_SMOKE,
    MENU_COLOR_WHITE,
};

enum MENU_WIFI_SETUP
{
    MENU_WIFI_NETWORK_ENABLED = 179, // WiFi toggle
    MENU_WIFI_NETWORK_SCAN = 180,    // Scan Networks
    MENU_WIFI_NETWORKS_NEARBY = 181, // Nearby Networks
    MENU_WIFI_PASSWORD = 182,        // Password (185)
    MENU_WIFI_HOSTNAME = 183,        // Hostname
    MENU_WIFI_IP_ADDR = 184,         // IP Address
    MENU_WIFI_MAC_ADDR = 199,        // IP Address
    MENU_WIFI_STATIC_ADDR = 198,     // Static IP
};

enum MENU_WIFI_STATIC
{
    MENU_WIFI_STATIC_ENABLED = 2050,
    MENU_WIFI_STATIC_IP = 2051,
    MENU_WIFI_STATIC_GATEWAY = 2052,
    MENU_WIFI_STATIC_NETMASK = 2053,
    MENU_WIFI_STATIC_DNS1 = 2055,
    MENU_WIFI_STATIC_DNS2 = 2056,
    MENU_WIFI_STATIC_ENABLED_VAR = 2060,
    MENU_WIFI_STATIC_IP_EDIT = 2061,
    MENU_WIFI_STATIC_GATEWAY_EDIT = 2062,
    MENU_WIFI_STATIC_NETMASK_EDIT = 2063,
    MENU_WIFI_STATIC_DNS1_EDIT = 2065,
    MENU_WIFI_STATIC_DNS2_EDIT = 2066,
    MENU_WIFI_STATIC_IP_SAVE = 2071,
    MENU_WIFI_STATIC_GATEWAY_SAVE = 2072,
    MENU_WIFI_STATIC_NETMASK_SAVE = 2073,
    MENU_WIFI_STATIC_DNS1_SAVE = 2075,
    MENU_WIFI_STATIC_DNS2_SAVE = 2076,
};

enum MENU_WIFI_HOSTNAME_EDIT
{
    MENU_WIFI_HOSTNAME_EDIT = 188,
    MENU_WIFI_HOSTNAME_SAVE = 189,
};

enum MENU_WIFI_PASSWORD
{
    MENU_WIFI_PASSWORD_SHOW = 185,          // Show Password
    MENU_WIFI_PASSWORD_NETWORK_JOIN = 186,  // Join Network
    MENU_WIFI_PASSWORD_DELETE_STORED = 187, // Delete stored network
    MENU_WIFI_PASSWORD_EDIT = 188,
    MENU_WIFI_PASSWORD_SAVE = 189,
    MENU_WIFI_PASSWORD_NETWORK_JOIN_ERROR = 3186,
    MENU_WIFI_PASSWORD_DELETE_STORED_ACK = 3187,
};

enum MENU_BLE_SETUP
{
    MENU_BLE_ENABLE = 190,
    MENU_BLE_MONITOR = 191,
};

enum MENU_USB_SETUP
{
    MENU_USB_ENABLE = 205,
    MENU_USB_MONITOR = 206,
    MENU_USB_DISCOVER = 207,
};

enum MENU_POWER_SETUP
{
    MENU_SYS_RESET = 210,
    MENU_SYS_POWER_OFF = 211,
};

enum MENU_RTC_SETUP
{
    MENU_RTC_CURRENT = 219,
    MENU_RTC_DATE_SET = 222,
    MENU_RTC_TIME_SET = 223,
    MENU_RTC_ALARM = 220,
    MENU_RTC_TIMER = 221,
};

enum MENU_RTC_SET_DATE
{
    MENU_RTC_SET_DATE_YEAR = 224,
    MENU_RTC_SET_DATE_MONTH = 225,
    MENU_RTC_SET_DATE_DAY = 226,
};

enum MENU_RTC_SET_TIME
{
    MENU_RTC_SET_TIME_HOUR = 227,
    MENU_RTC_SET_TIME_MINUTE = 228,
    MENU_RTC_SET_TIME_SECOND = 229,
};
enum MENU_SPAN_5
{
    MENU_SPAN_5_START = 51,
    MENU_SPAN_5_END = 56,
};

enum MENU_SPAN_7
{
    MENU_SPAN_7_START = 51,
    MENU_SPAN_7_END = 58,
};

enum MENU_SPAN_12
{
    MENU_SPAN_12_START = 51,
    MENU_SPAN_12_END = 63,
};

enum MENU_SPAN_24
{
    MENU_SPAN_24_START = 50,
    MENU_SPAN_24_END = 74,
};

enum MENU_SPAN_25
{
    MENU_SPAN_25_START = 51,
    MENU_SPAN_25_END = 75,
};

enum MENU_SPAN_31
{
    MENU_SPAN_31_START = 51,
    MENU_SPAN_31_END = 82,
};

enum MENU_SPAN_50
{
    MENU_SPAN_50_START = 50,
    MENU_SPAN_50_END = 100,
};

enum MENU_SPAN_60
{
    MENU_SPAN_60_START = 50,
    MENU_SPAN_60_END = 110,
};

enum MENU_SPAN_75
{
    MENU_SPAN_75_START = 50,
    MENU_SPAN_75_END = 125,
};

enum MENU_SPAN_A_Z
{

};

#endif